#!/bin/bash

source ~/rosenv
source ~/ws_alvar/devel/setup.bash --extend

#roslaunch ./alvar_baxter_vxlab.launch limb:="${arm}" marker_size:="${marker_size}"

roslaunch ./vxlab_bundle.launch limb:="${arm}" marker_size:="${marker_size}"
