#!/bin/bash

git checkout blue-mir100
git pull

# In case docker-compose does not kill all containers...
# docker rm -f gazebo vxlab-rosie-nav novnc display2 alvar-head alvar-right

export SIMTESTS=${1:-"vision_pickup_random_refactored pickup"}
export BAXTER_ONLY=true

./test $SIMTESTS
