#!/bin/bash

#git checkout blue-mir100
#git pull

# In case docker-compose does not kill all containers...
# docker rm -f gazebo vxlab-rosie-nav novnc display2 alvar-head alvar-right

case "$#" in
	1)
		export SIMTESTS=${1}
	;;
esac

# Do not spawn X applications interactively
export XDISPLAY=novnc:0

#docker-compose down --remove-orphans && docker-compose -f docker-compose.test.yml build && \
export GIT_COMMIT=`git rev-parse HEAD`
echo "running tests for commit $GIT_COMMIT" && \
  docker-compose -f docker-compose.yml -f docker-compose.test.yml up test
