#!/bin/bash
git checkout blue-mir100

#docker rm -f gazebo vxlab-rosie-nav novnc display2 alvar-head alvar-right
#docker-compose build && docker-compose -f docker-compose.yml -f docker-compose.test.yml up --force-recreate -d
docker-compose down --remove-orphans && docker-compose build && docker-compose -f docker-compose.yml up --force-recreate -d && \
  echo running tests && \
  docker-compose -f docker-compose.yml -f docker-compose.test.yml up --force-recreate -d test

docker logs -f test
