#!/bin/bash

echo run-tests... TESTS $TESTS

# set SCRIPTS to the directory containing this script
SOURCE="${BASH_SOURCE[0]}"
# While $SOURCE is a symlink, resolve it
while [ -h "$SOURCE" ]; do
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     SOURCE="$( readlink "$SOURCE" )"
     # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
     [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source ~/rosie/rosenv.gazebo.bash

DATE=`date '+%Y%m%d%H%M%S'`
REPORT_DIR=~/rosie/tests/test_results
mkdir -p $REPORT_DIR
OUT=$REPORT_DIR/results.${DATE}.out
#OUTDIR=$REPORT_DIR/output.${DATE}
OUTDIR=$REPORT_DIR
mkdir -p $OUTDIR

#TESTS="startup ${TESTS}"

echo TESTS: ${TESTS} | tee -a $OUT
echo BAXTER_ONLY: ${BAXTER_ONLY} | tee -a $OUT
echo OUTDIR: ${OUTDIR} | tee -a $OUT

for test in ${TESTS}
do
  $SCRIPTDIR/tests/$test > ${OUTDIR}/${test}.out 2>&1
  case $? in
    1) result=FAIL
    ;;
    0) result=PASS
    ;;
    *) result=UNKN
    ;;
  esac
  echo "***********************************"
  echo "**** $result: $test ****" |& tee -a $OUT
  echo "***********************************"
done
