#!/bin/bash

echo run-tests... TESTS $TESTS

# set SCRIPTS to the directory containing this script
SOURCE="${BASH_SOURCE[0]}"
# While $SOURCE is a symlink, resolve it
while [ -h "$SOURCE" ]; do
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     SOURCE="$( readlink "$SOURCE" )"
     # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
     [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPTDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

source ~/rosie/rosenv.gazebo.bash
set -xv

rm -f tests.out
touch tests.out

for test in $TESTS
do
  echo running $test | tee tests.out
  date | tee ${test}.out
  $SCRIPTDIR/tests/$test > ${test}.out 2>&1
  let "result = 1 - $?"
  echo "$test $result" |& tee tests.out
done
