#!/bin/bash

rosservice call /gazebo/delete_model cafe_table1
rosservice call /gazebo/delete_model cafe_table2
rosservice call /gazebo/delete_model marker0
rosservice call /gazebo/delete_model marker_s0

rosservice call /gazebo/delete_model marker_table
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markertable/model.sdf -model marker_table -x 2.0 -y 0.0 -z 0.0

#rosrun gazebo_ros spawn_model -sdf -file ~/rosie/cafe_table/model.sdf -model cafe_table1 -x 2.5 -y -0.5 -z 0.0

# large block
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock50_obj/model.sdf -model marker0 -x 3.0 -y -0.5 -z 0.9

# small block
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblockgrab_obj/model.sdf -model marker_s0 -x 2.1 -y -0.5 -z 0.9
