#!/bin/bash

#roll=${1:-0.0}
roll=${1:-1.56}
pitch=${2:-0.0}
#yaw=${3:-0.7}
yaw=${3:-0.0}

# Gazebo / Baxter drivers do not respond well to malformed deletes ... ?
# Appears to cause failure with error: "[FATAL] [1597221904.084218604]: The internal stop and start request lists are not empty at the beginning of the swithController() call. This should not happen."

function delete_model() {
  modelname=$1	 
  echo "Checking if model $modelname needs to be deleted"
  { ~/rosie/get_gazebo_models.py | egrep "'${modelname}'" ; } && echo Deleting $modelname && rosservice call /gazebo/delete_model $modelname
}

delete_model marker1

# master marker on top: ./spawn1 -1.56 0.0 0.0 (alvar: 0,0,-1.2)
# master marker on bot: ./spawn1 1.56 0.0 0.0  (alvar: 0,0,-1.2)
# master marker front: ./spawn1 -1.56 0.0 0.0  (alvar: 0,0,-1.2)
# FAILING: ../spawn1 0 0 0.8
# 0,1,2,4: ../spawn1 1.54 0 2.74

##########rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock_1/model.sdf -model marker1 -x 0.5 -y 0.03 -z 0.8 -R $roll -P $pitch -Y $yaw
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock_1/model.sdf -model marker1 -x 0.7 -y 0.1 -z 0.8 -R $roll -P $pitch -Y $yaw
