#!/bin/bash

rosservice call /gazebo/delete_model cafe_table1
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/cafe_table/model.sdf -model cafe_table1 -x 1.55 -y 0.0 -z 0.0

rosservice call /gazebo/delete_model cafe_table2
rosservice call /gazebo/delete_model markercafe_table2
rosrun gazebo_ros spawn_model -sdf -file ~/rosie/cafe_table/model.sdf -model cafe_table2 -x 2.5 -y 0.0 -z 0.0
