#!/bin/bash

#source ~/rosie/rosenv.common.bash
#source /opt/ros/melodic/setup.bash

ready=0
set -xv
while [ "$ready" -eq "0" ];
do
	echo 'Awaiting ROS master'
	rostopic pub /test_status std_msgs/String 'Test service started' -1 && ready=1
	sleep 1
done

echo 'Listening for events'


rostopic echo /rosie/sim/events/data &

# you may need to do something like this if containers are not successfully removed by docker-compose
#docker rm -f gazebo vxlab-rosie-nav novnc display2 alvar-head alvar-right

rostopic echo -n 1 --filter "m.data=='Sim started'" /rosie/sim/events/data | grep "Sim started"
