#!/bin/bash

#source ~/rosie/rosenv.common.bash
#source /opt/ros/melodic/setup.bash

ready=0
set -xv
while [ "$ready" -eq "0" ];
do
	echo 'Awaiting ROS master'
	rostopic pub /test_status std_msgs/String 'Test service started' -1 && ready=1
	sleep 1
done

cd ~/rosie/ikeg

# move Baxter arms out of the way
~/rosie/untuck
#./block_pickup_test_reset.py
~/rosie/spawn

delete_model marker1
#rosrun gazebo_ros spawn_model -sdf -file ~/rosie/markerblock_1/model.sdf -model marker1 -x 0.5 -y 0.03 -z 0.8 -Y 0.7 -P -0.0 -R -0.0
~/rosie/spawn_random.py 1

{ sleep 500 ; echo "$0 Timeout"; exit 1; } &

./pickup_alvar_demo.py
result=$?
echo "finished with result $result"

delete_model marker1
exit $result
